---
- name: get 5/6 repofile
  get_url: url=http://{{ fileServer }}/{{ item }} dest=/etc/yum.repos.d/ owner=root group=root mode=644
  with_items:
   - "{{ repofiles }}"
  when: "ansible_distribution_major_version in ['5','6']"

- name: get 7 repofile
  get_url: url=http://{{ fileServer }}/{{ item }} dest=/etc/yum.repos.d/ owner=root group=root mode=644
  with_items:
   - "{{ repofiles7 }}"
  when: "ansible_distribution_major_version == '7'"

